### PR TITLE
Apache Kafka 2.0 and latest of Strimzi

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
I am getting `CrashLoopBackOff` w/ v3.10 .. (but worked earlier) - getting them w/ vanilla Strimzi 0.6 as well... :cry: 

I am now trying 3.9 ...

@hhiden, @sjwoodman feel free to also give this a shot (NOTE: due to CRDs our Eventlfow may niot work, since it's based on CMs)

**Comment by matzew** [comment]
Looks like it does require the `CRD`s for both:
* kafkaconnect
* kafkaconnects2i

Added them now

**Comment by matzew** [comment]
Tested on both OKD 3.9 and 3.10 - on a Fedora Linux machine.

worked great

**Comment by sjwoodman** [comment]
Works for me on 3.9 👍

**Pull request merged**
